server:
  port: 6789

netty:
  port: 8889
  bossThreadCount: 200
  workThreadCount: 200

spring:
  # mysql配置
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/spring_boot?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver

  # redis配置
  redis:
    host: 127.0.0.1
    port: 6379
    password: pass1234
    timeout: 0
    pool:
      max-active: 100     # 最大活跃连接数
      max-idle: 10        # 最大空闲连接数
      max-wait: 100000    # 创建链接的超时时间
      min-idle: 2         # 最小空闲连接数
